workflows:
  ios-build:
    name: Build iOS App
    max_build_duration: 60
    jobs:
      - name: Build iOS App
        macos: true  # Menentukan bahwa pekerjaan ini membutuhkan macOS runner
        script:
          - flutter pub get  # Mendapatkan dependensi Flutter
          - flutter build ios --release --no-codesign  # Membangun aplikasi iOS dalam mode release tanpa penandatanganan kode
